Looben/urls.py
from cgitb import handler
import sre_compile
from django.contrib import admin
from django.urls import path, include 
from django.conf import settings
from django.conf.urls.static import static

from accounts.views import page_not_found, server_error


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('reviews.urls')),
    path('', include('dashboard.urls')),
    path('', include('job.urls')),
    path('', include('study_abroad_information.urls')),
    path('', include('questions.urls')),
    path('', include('chat.urls')),
    path('', include('contact_form.urls')),
    path('', include('notifications.urls')),
]

handler404 = page_not_found
handler500 = server_error

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('comingsoon/', views.ComingSoonView.as_view(), name='comingsoon'),
    path('regist/', views.RegistUserView.as_view(), name='regist'),
    path('user_login/', views.UserLoginView.as_view(), name='user_login'),
    path('user_logout/', views.UserLogoutView.as_view(), name='user_logout'),
    path('<slug:username>/account_setting', views.AccountSettingView.as_view(), name='account_setting'),
    path('password_change/', views.password_change, name='password_change'),
    path('user_ranking/', views.UserRankingView.as_view(), name='user_ranking'),
    path('research_university/', views.ResearchUniversity.as_view(), name='research_university'),
    path('follow_for_user/', views.follow_for_user_view, name='follow_for_user'),
    path('like_for_university/', views.like_for_university_view, name='like_for_university'),
    path('university_detail/<int:pk>', views.UniversityDetailView.as_view(), name='university_detail'),
    path('students_by_university/<int:pk>', views.StudentsByUniversityView.as_view(), name='students_by_university'),
]

dashboard/urls.py
from django.urls import path 

from . import views

app_name = 'dashboard'

urlpatterns = [
    path('<slug:username>/post_in_dashboard', views.PostInDashboardView.as_view(), name='post_in_dashboard'),
    path('<slug:username>/review_in_dashboard', views.ReviewInDashboardView.as_view(), name='review_in_dashboard'),
    path('<slug:username>/following_in_dashboard', views.FollowingInDashboardView.as_view(), name='following_in_dashboard'),
    path('<slug:username>/followed_in_dashboard', views.FollowedInDashboardView.as_view(), name='followed_in_dashboard'),
    path('<slug:username>/question_in_dashboard', views.QuestionInDashboardView.as_view(), name='question_in_dashboard'),
]

job/urls.py
from django.urls import path
from . import views


app_name = 'job'

urlpatterns = [
        path('create_job_experience/', views.create_job_experience, name='create_job_experience'),
        path('update_job_experience/<int:pk>', views.UpdateJobExperienceView.as_view(), name='update_job_experience'),
        path('delete_job_experience/<int:pk>', views.DeleteJobExperienceView.as_view(), name='delete_job_experience'),
]

questions/urls.py
from django.urls import path
from . import views

app_name = 'questions'

urlpatterns = [
    path('question/', views.QuestionView.as_view(), name='question'),
    path('ask_question/', views.ask_question, name='ask_question'),
    path('<slug:category>/categorized_questions', views.CategorizedQuestionsView.as_view(), name='categorized_questions'),
    path('list_of_questions_for_each_university/<int:pk>', views.ListOfQuestionsForEachUniversity.as_view(), name='list_of_questions_for_each_university'),
    path('decide_and_comment_to_best_answer/<int:pk>', views.DecideAndCommentToBestAnswer.as_view(), name='decide_and_comment_to_best_answer'),
    path('question_detail/<int:pk>', views.QuestionDetailView.as_view(), name='question_detail'),
]

reviews/urls.py
from django.urls import path
from . import views

app_name = 'reviews'

urlpatterns = [
    path('create_review/', views.create_review_of_university, name='create_review_of_university'),
    path('review_list_of_universities/<int:pk>', views.ReviewListOfUniversities.as_view(), name='review_list_of_universities'),
    path('delete_review/<int:pk>', views.DeleteReviewView.as_view(), name='delete_review'),
]

reviews/models.py
from time import timezone
from django.db import models
from django.utils import timezone
from django.core.validators import MinValueValidator,MaxValueValidator

from accounts.models import Schools, Users


class ReviewOfUniversity(models.Model):
    title = models.CharField(max_length=100)
    review = models.TextField(max_length=300)
    created_at = models.DateTimeField(default=timezone.now)
    star = models.IntegerField(default=5)
    user = models.ForeignKey(
        Users, on_delete=models.CASCADE
    )
    university = models.ForeignKey(
        Schools, on_delete=models.CASCADE
    )
    
    class Meta:
        db_table = 'review_of_university'
        verbose_name_plural = '口コミ'
        
    def __str__(self):
        return self.title + ' : ' + str(self.user)
    
    

reviews/forms.py
from dataclasses import field
from django import forms
from django.contrib.auth.password_validation import validate_password
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.admin.widgets import AdminDateWidget

from .models import ReviewOfUniversity
from accounts.models import Schools


class ReviewForm(forms.ModelForm):
    title = forms.CharField(label='タイトル', widget=forms.TextInput(attrs={
        'class': 'form-control', 
        'placeholder': 'タイトル',
        'type': 'text',
        }))
    review = forms.CharField(label='レビュー', widget=forms.Textarea(attrs={
        'class': 'form-control', 
        'placeholder': '口コミ本文',
        'rows': '8',
        'type': 'textarea',
        }))
    university = forms.ModelChoiceField(label='大学', queryset= Schools.objects.all(), widget=forms.Select(attrs={
        'class': 'form-control', 
        'placeholder': 'レビューを書く大学',
        'type': 'select',
        }))
    star = forms.ChoiceField(label='総合評価', choices=((1, 'とても良くない'), (2, '良くない'), (3, '普通'), (4, '良い'), (5, 'とても良い')), widget=forms.Select(attrs={
        'class': 'form-control', 
        'placeholder': '総合評価',
        'type': 'select',
        }))
    
    class Meta:
        model = ReviewOfUniversity
        fields = ['title', 'review', 'university', 'star'] 

reviews/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic.detail import DetailView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.urls import reverse_lazy
from django.views.generic.edit import DeleteView
from django.shortcuts import get_object_or_404  
from django.http import JsonResponse

from .models import ReviewOfUniversity
from .forms import ReviewForm

from accounts.models import Schools, FollowForUser
from accounts import contribution_calculation
from chat.models import ConversationPartner
from notifications.models import Notification


@login_required
def create_review_of_university(request):
    create_review_form = ReviewForm(request.POST or None)
    if create_review_form.is_valid():
        create_review_form.instance.user = request.user
        create_review_form.save()
        messages.success(request, 'レビューを作成しました')
        # Start -Schoolsの星評価にこのレビューの評価を反映させる-
        target_university = Schools.objects.get(id=create_review_form.cleaned_data.get('university').id)
        review_list_for_target_university = ReviewOfUniversity.objects.filter(university=target_university).all()
        # get the value of total added rating
        total_added_rating_value = int(create_review_form.cleaned_data.get('star'))
        number_of_review = len(review_list_for_target_university) + 1
        for review in review_list_for_target_university:
            total_added_rating_value += int(review.star)
        target_university.star_rating = total_added_rating_value / number_of_review
        target_university.save()
        # End -Schoolsの星評価にこのレビューの評価を反映させる-
        contribution_calculation.for_creating_review(user=request.user)
        # フォロワーへ口コミ作成の通知を作成
        for follow in FollowForUser.objects.filter(followed_user=request.user).all():
            create_review_notification = Notification(sender=request.user, receiver=follow.user, message= str(request.user.username) + 'が新しく口コミを投稿しました。')
            create_review_notification.save()
        return redirect('accounts:research_university')
    notification_lists =  Notification.objects.filter(receiver=request.user).order_by('timestamp').reverse()[:3]
    number_of_notification =  Notification.objects.filter(receiver=request.user).count()
    has_notifications =  Notification.objects.filter(receiver=request.user).exists()
    has_not_seen_message = ConversationPartner.objects.filter(current_user=request.user, have_new_message=True).exists()
    return render(
        request, 'reviews/create_review_of_university.html', context={
            'create_review_form': create_review_form,
            'notification_lists': notification_lists,
            'number_of_notification': number_of_notification,
            'has_notifications': has_notifications,
            'has_not_seen_message': has_not_seen_message
        }
    )
    
    
class ReviewListOfUniversities(DetailView):
    model = Schools
    template_name = 'reviews/review_list_of_universities.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        school = self.object
        context['reviews'] = ReviewOfUniversity.objects.filter(university=school)
        context['notification_lists'] =  Notification.objects.filter(receiver=self.request.user).order_by('timestamp').reverse()[:3]
        context['number_of_notification'] =  Notification.objects.filter(receiver=self.request.user).count()
        context['has_notifications'] =  Notification.objects.filter(receiver=self.request.user).exists()
        context['has_not_seen_message'] = ConversationPartner.objects.filter(current_user=self.request.user, have_new_message=True).exists()
        return context


class CheckForUserMatchMixin(LoginRequiredMixin, UserPassesTestMixin):
    
    def test_func(self):
        target_review = get_object_or_404(ReviewOfUniversity, pk=self.kwargs['pk'])
        return self.request.user == target_review.user
        
    def handle_no_permission(self):
        return JsonResponse(
            {'message': 'Only user who made this author have access to this view'}
        )
    
    
class DeleteReviewView(CheckForUserMatchMixin, DeleteView):
    template_name = 'reviews/delete_review.html'
    model = ReviewOfUniversity
    
    def get_success_url(self):
        return reverse_lazy('dashboard:review_in_dashboard', kwargs={'username': self.object.user.username})
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['notification_lists'] =  Notification.objects.filter(receiver=self.request.user).order_by('timestamp').reverse()[:3]
        context['number_of_notification'] =  Notification.objects.filter(receiver=self.request.user).count()
        context['has_notifications'] =  Notification.objects.filter(receiver=self.request.user).exists()
        context['has_not_seen_message'] = ConversationPartner.objects.filter(current_user=self.request.user, have_new_message=True).exists()
        return context

templates/reviews/create_review_of_university.html
{% extends 'base.html' %}
{% load static %}


{% block head_content%}
    <link rel="stylesheet" href="{% static 'css/accounts/message.css' %}">
{% endblock %}


{% block header %}
{% include 'header.html' %}
{% endblock %}


{% block content %}
<!-- **************** MAIN CONTENT START **************** -->
<main>
    <!-- Container START -->
    <div class="container">
      <div class="row g-4">
  
        <!-- Sidenav START -->
        <div class="col-lg-3">
  
          <!-- Advanced filter responsive toggler START -->
          <div class="d-flex align-items-center d-lg-none">
            <button class="border-0 bg-transparent" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasSideNavbar" aria-controls="offcanvasSideNavbar">
              <i class="btn btn-primary fw-bold fa-solid fa-sliders-h"></i>
              <span class="h6 mb-0 fw-bold d-lg-none ms-2">マイプロフィール</span>
            </button>
          </div>
          <!-- Advanced filter responsive toggler END -->
          
          <!-- Navbar START-->
          <nav class="navbar navbar-expand-lg mx-0"> 
            <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasSideNavbar">
              <!-- Offcanvas header -->
              <div class="offcanvas-header">
                <button type="button" class="btn-close text-reset ms-auto" data-bs-dismiss="offcanvas" aria-label="Close"></button>
              </div>
  
              <!-- Offcanvas body -->
              <div class="offcanvas-body d-block px-2 px-lg-0">
                <!-- Card START -->
                <div class="card overflow-hidden">
                  <!-- Cover image -->
                  <div class="h-50px" style="background-image:url({% static 'images/bg/create_review.jpg' %}); background-position: center; background-size: cover; background-repeat: no-repeat;"></div>
                    <!-- Card body START -->
                    <div class="card-body pt-0">
                      <div class="text-center">
                      <!-- Avatar -->
                      <div class="avatar avatar-lg mt-n5 mb-3">
                        <a href="#!"><img class="avatar-img rounded border border-white border-3" src="{{ user.picture.url }}" alt="{{ user.username }}"></a>
                      </div>
                      <!-- Info -->
                      <h5 class="mb-0"> 
                        <a href="{% url 'dashboard:post_in_dashboard' user.username %}">
                          {{ user.name }} 
                          {% if user.is_verified %}
                          <i class="bi bi-patch-check-fill text-primary small"></i>
                          {% endif %}
                        </a> 
                      </h5>
                      <p>{{ user.school }}</p>

                    </div>
                    <!-- Divider -->
                    <hr>
  
                    <!-- Side Nav START -->
                    <ul class="nav nav-link-secondary flex-column fw-bold gap-2 text-center">
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:account_setting' user.username %}"> <img class="me-2 h-20px fa-fw" src="{% static 'images/icon/settings-outline-filled.svg'%}" alt=""><span>設定 </span></a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:account_setting' user.username %}"> <img class="me-2 h-20px fa-fw" src="{% static 'images/icon/person-outline-filled.svg'%}" alt=""><span>友達 </span></a>
                      </li>
                    </ul>
                    <!-- Side Nav END -->
                  </div>
                  <!-- Card body END -->
                  <!-- Card footer -->
                  <div class="card-footer text-center py-2">
                    <a class="btn btn-link btn-sm" href="{% url 'dashboard:post_in_dashboard' user.username %}">ダッシュボードを見る </a>
                  </div>
                </div>
                <!-- Card END -->

                <!-- Copyright -->
                <p class="small text-center mt-1">©2023 <a class="text-body" target="_blank" href=""> Looben </a></p>
              </div>
            </div>
          </nav>
          <!-- Navbar END-->
        </div>
        <!-- Sidenav END -->
  
        <!-- Main content START -->
        <div class="col-md-8 col-lg-6 vstack gap-4">
          <!-- Create a page START -->
          <div class="card">
            <!-- Title START -->
            <div class="card-header border-0 pb-0">
              <h1 class="h4 card-title mb-0">大学口コミ作成ページ</h1>
            </div>
            <!-- Title END -->

            <!-- Create a page form START -->
            <div class="card-body">
              <form class="row g-3 mt-4" method="post">
                {{ create_review_form.non_field_errors }}
                {% csrf_token %}

                <!-- 口コミ大学 -->
                <div class="col-8">
                  <label class="form-label">口コミをする大学</label>
                  {{ create_review_form.university }}
                  <small>自分が詳しい大学について役立つ情報を書いてみよう</small>
                </div>
                {{ create_review_form.university.errors }}

                <!-- 総合評価 -->
                <div class="col-8">
                  <label class="form-label">総合評価(おすすめ度)</label>
                  {{ create_review_form.star }}
                  <small>この評価は、大学の総合評価に反映されます</small>
                </div>
                {{ create_review_form.star.errors }}

                <!-- タイトル -->
                <div class="col-12">
                  <label class="form-label">タイトル</label>
                  {{ create_review_form.title }}
                  <small>内容を簡潔に表すようなタイトルだとGood</small>
                </div>
                {{ create_review_form.title.errors }}

                <!-- レビュー本文 -->
                <div class="col-12">
                  <label class="form-label">レビュー</label>
                  {{ create_review_form.review }}
                  <small>個人名を出したり、不快になるような言葉は避けましょう（文字制限300字）</small>
                </div>
                {{ create_review_form.review.errors }}

                <!-- Button  -->
                <div class="col-12 text-end">
                  <button type="submit" class="btn btn-primary mb-0">口コミを作成</button>
                </div>
              </form>
            </div>
            <!-- Create a page form END -->
          </div>
          <!-- Create a page END -->
        </div>
  
      </div> <!-- Row END -->
    </div>
    <!-- Container END --> 
</main>
<!-- **************** MAIN CONTENT END **************** -->
{% endblock %}

templates/reviews/review_list_of_universities.html
{% extends 'base.html' %}
{% load static %}


{% block head_content%}
    <link rel="stylesheet" href="{% static 'css/accounts/message.css' %}">
{% endblock %}



{% block header %}
{% include 'header.html' %}
{% endblock %}


{% block content %}
<!-- **************** MAIN CONTENT START **************** -->
<main>
    <!-- Container START -->
    <div class="container">
      <div class="row g-4">

        <!-- Sidenav START -->
        <div class="col-lg-3">
  
          <!-- Advanced filter responsive toggler START -->
          <div class="d-flex align-items-center d-lg-none">
            <button class="border-0 bg-transparent" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasSideNavbar" aria-controls="offcanvasSideNavbar">
              <i class="btn btn-primary fw-bold fa-solid fa-sliders-h"></i>
              <span class="h6 mb-0 fw-bold d-lg-none ms-2">{{ object.name }}</span>
            </button>
          </div>
          <!-- Advanced filter responsive toggler END -->
          
          <!-- Navbar START-->
          <nav class="navbar navbar-expand-lg mx-0"> 
            <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasSideNavbar">
              <!-- Offcanvas header -->
              <div class="offcanvas-header">
                <button type="button" class="btn-close text-reset ms-auto" data-bs-dismiss="offcanvas" aria-label="Close"></button>
              </div>
  
              <!-- Offcanvas body -->
              <div class="offcanvas-body d-block px-2 px-lg-0">
                <!-- Card START -->
                <div class="card overflow-hidden">
                  <!-- Cover image -->
                  <div class="h-50px" style="background-image:url({% static 'images/bg/create_review.jpg' %}); background-position: center; background-size: cover; background-repeat: no-repeat;"></div>
                    <!-- Card body START -->
                    <div class="card-body pt-0">
                      <div class="text-center">
                      <!-- Avatar -->
                      <div class="avatar avatar-lg mt-n5 mb-3">
                        <a href="#!"><img class="avatar-img rounded border border-white border-3" src="{% static 'images/Yuan_Ze_University_Logo.png' %}" alt="{{ object.name }}"></a>
                      </div>
                      <!-- Info -->
                      <h5 class="mb-0"> <a href="{% url 'accounts:university_detail' object.id %}">{{ object.name }} </a> </h5>
                      <p>{{ object.sub_title }}</p>
                      {% with range=''|center:5 %}
                      {% for _ in range %}
                        {% if forloop.counter <= object.star_rating %}
                        <i class="fas fa-star" style="color:#F7E36C;"></i>
                        {% else %}
                        <i class="fas fa-star" style="color:#D8DDEA;"></i>
                        {% endif %}
                      {% endfor %}
                      <span style="color:#FF1474;"><strong>{{ object.star_rating }}.0</strong></span>
                      {% endwith %}
                    </div>
                    <!-- Divider -->
                    <hr>
  
                    <!-- Side Nav START -->
                    <ul class="nav nav-link-secondary flex-column fw-bold gap-2 text-center">
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:students_by_university' object.id %}"> <img class="me-2 h-20px fa-fw" src="{% static 'images/icon/person-outline-filled.svg'%}" alt="student"><span>在校生 </span></a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'questions:list_of_questions_for_each_university' object.id %}"> <img class="me-2 h-20px fa-fw" src="{% static 'images/icon/search-outline-filled.svg'%}" alt="question"><span>質問 </span></a>
                      </li>
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'reviews:review_list_of_universities' object.id %}"> <img class="me-2 h-20px fa-fw" src="{% static 'images/icon/clipboard-outline-filled.svg'%}" alt="review"><span>口コミ </span></a>
                      </li>
                    </ul>
                    <!-- Side Nav END -->
                  </div>
                  <!-- Card body END -->
                  <!-- Card footer -->
                  <div class="card-footer text-center py-2">
                    <a class="btn btn-link btn-sm" href="{% url 'accounts:university_detail' object.id %}">大学詳細ページに戻る </a>
                  </div>
                </div>
                <!-- Card END -->

                <!-- Copyright -->
                <p class="small text-center mt-1">©2023 <a class="text-body" target="_blank" href=""> Looben </a></p>
              </div>
            </div>
          </nav>
          <!-- Navbar END-->
        </div>
        <!-- Sidenav END -->
  
        <!-- Main content START -->
        <div class="col-md-8 col-lg-6 vstack gap-4">
          <!-- Create a page START -->
          <div class="card">
            <!-- Title START -->
            <div class="card-header border-0 pb-0">
              <h1 class="h4 card-title mb-0">大学口コミ一覧</h1>
            </div>
            <!-- Title END -->

            <!-- Create a page form START -->
            <div class="card-body">
                <div class="mt-4 mt-sm-5" id="review">          
                    <div class="accordion accordion-icon" id="accordionschedules">
                      {% for review in reviews %}
                        {% if forloop.counter == 1 %}
                        <!-- Accordion item -->
                        <div class="accordion-item mb-3">
                          <div class="accordion-header" id="schedule{{ review.title }}">
                            <button class="accordion-button pe-5 flex-wrap fw-bold" type="button" data-bs-toggle="collapse" data-bs-target="#schedulecollapse{{ review.title }}" aria-expanded="true" aria-controls="schedulecollapse{{ review.title }}">
                              <strong>{{ review.title }}</strong>
                              <div>
                                <div>
                                {% with range=''|center:5 %}
                                {% for _ in range %}
                                  {% if forloop.counter <= review.star %}
                                  <i class="fas fa-star" style="color:#F7E36C;"></i>
                                  {% else %}
                                  <i class="fas fa-star" style="color:#D8DDEA;"></i>
                                  {% endif %}
                                {% endfor %}
                                {% endwith %}
                                <span style="color:#FF1474;">{{ review.star }}.0</span>
                                </div>
                              </div>
                            </button>
                          </div>
                          <!-- Accordion info -->
                          <div id="schedulecollapse{{ review.title }}" class="accordion-collapse collapse show" aria-labelledby="schedule{{ review.title }}" data-bs-parent="#accordionschedules">
                            <div class="accordion-body">
                              <p>{{ review.review }}</p>
                              <p style="text-align:right;">{{ review.created_at }}</p>
                              <div class="row g-4">
                                <div class="col-12">
                                  <h5 class="mb-0">Speaker</h5>
                                </div>
                                <div class="col-sm-4 col-lg-3">
                                  <!-- Host Item -->
                                  <div class="card card-body text-center">
                                    <div class="avatar avatar-lg mx-auto mb-3"> 
                                      <a href="{% url 'dashboard:post_in_dashboard' review.user.username %}"><img class="avatar-img rounded-circle" src="{{ review.user.picture.url }}" alt="{{ review.user.username }}"></a>
                                    </div>
                                    <!-- Host name -->
                                    <div>
                                      <a href="{% url 'dashboard:post_in_dashboard' review.user.username %}">
                                        <h6 class="mb-0">
                                          {{ review.user.name }} 
                                          {% if review.user.is_verified %}
                                          <i class="bi bi-patch-check-fill text-primary small"></i>
                                          {% endif %}
                                        </h6>
                                      </a>
                                      <span>{{ review.user.school }}</span>
                                    </div>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                        {% else %}
                        <!-- Accordion item -->
                        <div class="accordion-item mb-3">
                          <div class="accordion-header" id="schedule{{ review.title }}">
                            <button class="accordion-button pe-5 flex-wrap fw-bold collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#schedulecollapse{{ review.title }}" aria-expanded="false" aria-controls="schedulecollapse{{ review.title }}">
                              <strong>{{ review.title }}</strong>
                              <div>
                                <div>
                                {% with range=''|center:5 %}
                                {% for _ in range %}
                                  {% if forloop.counter <= review.star %}
                                  <i class="fas fa-star" style="color:#F7E36C;"></i>
                                  {% else %}
                                  <i class="fas fa-star" style="color:#D8DDEA;"></i>
                                  {% endif %}
                                {% endfor %}
                                {% endwith %}
                                <span style="color:#FF1474;">{{ review.star }}.0</span>
                                </div>
                              </div>
                            </button>
                          </div>
                          <!-- Accordion info -->
                          <div id="schedulecollapse{{ review.title }}" class="accordion-collapse collapse" aria-labelledby="schedule{{ review.title }}" data-bs-parent="#accordionschedules">
                            <div class="accordion-body">
                              <p>{{ review.review }}</p>
                              <p style="text-align:right;">{{ review.created_at }}</p>
                              <div class="row g-4">
                                <div class="col-12">
                                  <h5 class="mb-0">Speaker</h5>
                                </div>
                                <div class="col-sm-4 col-lg-3">
                                  <!-- Host Item -->
                                  <div class="card card-body text-center">
                                    <div class="avatar avatar-lg mx-auto mb-3"> 
                                      <a href="{% url 'dashboard:post_in_dashboard' review.user.username %}"><img class="avatar-img rounded-circle" src="{{ review.user.picture.url }}" alt="{{ review.user.username }}"></a>
                                    </div>
                                    <!-- Host name -->
                                    <div>
                                      <a href="{% url 'dashboard:post_in_dashboard' review.user.username %}">
                                        <h6 class="mb-0">
                                          {{ review.user.name }} 
                                          {% if review.user.is_verified %}
                                          <i class="bi bi-patch-check-fill text-primary small"></i>
                                          {% endif %}
                                        </h6>
                                      </a>
                                      <span>{{ review.user.school }}</span>
                                    </div>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                        {% endif %}
                      {% empty %}
                      <p>レビューはまだありません。</p>
                      {% endfor %}
                    </div>
                </div>
            </div>
            <!-- Create a page form END -->
          </div>
          <!-- Create a page END -->
        </div>
  
      </div> <!-- Row END -->
    </div>
    <!-- Container END --> 
</main>
<!-- **************** MAIN CONTENT END **************** -->
{% endblock %}