Looben/urls.py
from cgitb import handler
import sre_compile
from django.contrib import admin
from django.urls import path, include 
from django.conf import settings
from django.conf.urls.static import static

from accounts.views import page_not_found, server_error


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('reviews.urls')),
    path('', include('dashboard.urls')),
    path('', include('job.urls')),
    path('', include('study_abroad_information.urls')),
    path('', include('questions.urls')),
    path('', include('chat.urls')),
    path('', include('contact_form.urls')),
    path('', include('notifications.urls')),
]

handler404 = page_not_found
handler500 = server_error

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('comingsoon/', views.ComingSoonView.as_view(), name='comingsoon'),
    path('regist/', views.RegistUserView.as_view(), name='regist'),
    path('user_login/', views.UserLoginView.as_view(), name='user_login'),
    path('user_logout/', views.UserLogoutView.as_view(), name='user_logout'),
    path('<slug:username>/account_setting', views.AccountSettingView.as_view(), name='account_setting'),
    path('password_change/', views.password_change, name='password_change'),
    path('user_ranking/', views.UserRankingView.as_view(), name='user_ranking'),
    path('research_university/', views.ResearchUniversity.as_view(), name='research_university'),
    path('follow_for_user/', views.follow_for_user_view, name='follow_for_user'),
    path('like_for_university/', views.like_for_university_view, name='like_for_university'),
    path('university_detail/<int:pk>', views.UniversityDetailView.as_view(), name='university_detail'),
    path('students_by_university/<int:pk>', views.StudentsByUniversityView.as_view(), name='students_by_university'),
]

chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'

urlpatterns = [
    path('chat/<str:username>', views.get_message, name='get_message'),
    path('chat_room/', views.ChatRoomView.as_view(), name='chat_room'),  
    path('api/messages/<int:sender>/<int:receiver>', views.UpdateMessage.as_view()), 
    path('create_chatroom/<str:username>', views.create_chatroom, name='create_chatroom')
]

dashboard/urls.py
from django.urls import path 

from . import views

app_name = 'dashboard'

urlpatterns = [
    path('<slug:username>/post_in_dashboard', views.PostInDashboardView.as_view(), name='post_in_dashboard'),
    path('<slug:username>/review_in_dashboard', views.ReviewInDashboardView.as_view(), name='review_in_dashboard'),
    path('<slug:username>/following_in_dashboard', views.FollowingInDashboardView.as_view(), name='following_in_dashboard'),
    path('<slug:username>/followed_in_dashboard', views.FollowedInDashboardView.as_view(), name='followed_in_dashboard'),
    path('<slug:username>/question_in_dashboard', views.QuestionInDashboardView.as_view(), name='question_in_dashboard'),
]

job/urls.py
from django.urls import path
from . import views


app_name = 'job'

urlpatterns = [
        path('create_job_experience/', views.create_job_experience, name='create_job_experience'),
        path('update_job_experience/<int:pk>', views.UpdateJobExperienceView.as_view(), name='update_job_experience'),
        path('delete_job_experience/<int:pk>', views.DeleteJobExperienceView.as_view(), name='delete_job_experience'),
]

questions/urls.py
from django.urls import path
from . import views

app_name = 'questions'

urlpatterns = [
    path('question/', views.QuestionView.as_view(), name='question'),
    path('ask_question/', views.ask_question, name='ask_question'),
    path('<slug:category>/categorized_questions', views.CategorizedQuestionsView.as_view(), name='categorized_questions'),
    path('list_of_questions_for_each_university/<int:pk>', views.ListOfQuestionsForEachUniversity.as_view(), name='list_of_questions_for_each_university'),
    path('decide_and_comment_to_best_answer/<int:pk>', views.DecideAndCommentToBestAnswer.as_view(), name='decide_and_comment_to_best_answer'),
    path('question_detail/<int:pk>', views.QuestionDetailView.as_view(), name='question_detail'),
]

reviews/urls.py
from django.urls import path
from . import views

app_name = 'reviews'

urlpatterns = [
    path('create_review/', views.create_review_of_university, name='create_review_of_university'),
    path('review_list_of_universities/<int:pk>', views.ReviewListOfUniversities.as_view(), name='review_list_of_universities'),
    path('delete_review/<int:pk>', views.DeleteReviewView.as_view(), name='delete_review'),
]

dashboard/models.py
from django.db import models



    

dashboard/forms.py
from dataclasses import field
from django import forms

dashboard/views.py
from django.views.generic.detail import DetailView

from accounts.models import Users, FollowForUser
from study_abroad_information.models import StudyAbroadInformation
from chat.models import ConversationPartner
from reviews.models import ReviewOfUniversity
from job.models import JobExperience
from notifications.models import Notification



class PostInDashboardView(DetailView):
    model = Users
    template_name = 'dashboard/post_in_dashboard.html'
    slug_field = 'username'
    slug_url_kwarg = 'username'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.object
        context['number_of_following_user'] = FollowForUser.objects.filter(user=user).count()
        context['number_of_followed_user'] = FollowForUser.objects.filter(followed_user=user).count()
        context['information_posts'] = StudyAbroadInformation.objects.filter(author=user).order_by('created_at').reverse().all()
        context['job_experiences'] = JobExperience.objects.filter(user=user).order_by('job_date').reverse().all()
        context['newest_users_list'] = Users.objects.filter(state='現役台湾留学生').order_by('joined_at').reverse()[:4]
        if user != self.request.user:
            context['is_user_following'] = FollowForUser.objects.filter(user=self.request.user, followed_user=user).exists()
            if context['is_user_following']:
                context['following_message_for_javascript'] = 'フォロー中'
            else:
                context['following_message_for_javascript'] = 'フォロー'
        context['notification_lists'] =  Notification.objects.filter(receiver=self.request.user).order_by('timestamp').reverse()[:3]
        context['number_of_notification'] =  Notification.objects.filter(receiver=self.request.user).count()
        context['has_notifications'] =  Notification.objects.filter(receiver=self.request.user).exists()
        context['has_not_seen_message'] = ConversationPartner.objects.filter(current_user=self.request.user, have_new_message=True).exists()
        return context
    
    
class ReviewInDashboardView(DetailView):
    model = Users
    template_name = 'dashboard/review_in_dashboard.html'
    slug_field = 'username'
    slug_url_kwarg = 'username'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.object
        context['number_of_following_user'] = FollowForUser.objects.filter(user=user).count()
        context['number_of_followed_user'] = FollowForUser.objects.filter(followed_user=user).count()
        context['reviews'] = ReviewOfUniversity.objects.filter(user=user).order_by('created_at').reverse().all()
        context['job_experiences'] = JobExperience.objects.filter(user=user).order_by('job_date').reverse().all()
        context['newest_users_list'] = Users.objects.filter(state='現役台湾留学生').order_by('joined_at').reverse()[:4]
        if user != self.request.user:
            context['is_user_following'] = FollowForUser.objects.filter(user=self.request.user, followed_user=user).exists()
            if context['is_user_following']:
                context['following_message_for_javascript'] = 'フォロー中'
            else:
                context['following_message_for_javascript'] = 'フォロー'
        context['notification_lists'] =  Notification.objects.filter(receiver=self.request.user).order_by('timestamp').reverse()[:3]
        context['number_of_notification'] =  Notification.objects.filter(receiver=self.request.user).count()
        context['has_notifications'] =  Notification.objects.filter(receiver=self.request.user).exists()
        context['has_not_seen_message'] = ConversationPartner.objects.filter(current_user=self.request.user, have_new_message=True).exists()
        return context
    

class FollowingInDashboardView(DetailView):
    model = Users
    template_name = 'dashboard/following_in_dashboard.html'
    slug_field = 'username'
    slug_url_kwarg = 'username'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.object
        context['number_of_following_user'] = FollowForUser.objects.filter(user=user).count()
        context['number_of_followed_user'] = FollowForUser.objects.filter(followed_user=user).count()
        context['job_experiences'] = JobExperience.objects.filter(user=user).order_by('job_date').reverse().all()
        context['newest_users_list'] = Users.objects.filter(state='現役台湾留学生').order_by('joined_at').reverse()[:4]
        if user != self.request.user:
            context['is_user_following'] = FollowForUser.objects.filter(user=self.request.user, followed_user=user).exists()
            if context['is_user_following']:
                context['following_message_for_javascript'] = 'フォロー中'
            else:
                context['following_message_for_javascript'] = 'フォロー'
        context['notification_lists'] =  Notification.objects.filter(receiver=self.request.user).order_by('timestamp').reverse()[:3]
        context['number_of_notification'] =  Notification.objects.filter(receiver=self.request.user).count()
        context['has_notifications'] =  Notification.objects.filter(receiver=self.request.user).exists()
        context['has_not_seen_message'] = ConversationPartner.objects.filter(current_user=self.request.user, have_new_message=True).exists()
        return context
    
    
class FollowedInDashboardView(DetailView):
    model = Users
    template_name = 'dashboard/followed_in_dashboard.html'
    slug_field = 'username'
    slug_url_kwarg = 'username'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.object
        context['number_of_following_user'] = FollowForUser.objects.filter(user=user).count()
        context['number_of_followed_user'] = FollowForUser.objects.filter(followed_user=user).count()
        context['job_experiences'] = JobExperience.objects.filter(user=user).order_by('job_date').reverse().all()
        context['newest_users_list'] = Users.objects.filter(state='現役台湾留学生').order_by('joined_at').reverse()[:4]
        if user != self.request.user:
            context['is_user_following'] = FollowForUser.objects.filter(user=self.request.user, followed_user=user).exists()
            if context['is_user_following']:
                context['following_message_for_javascript'] = 'フォロー中'
            else:
                context['following_message_for_javascript'] = 'フォロー'
        context['notification_lists'] =  Notification.objects.filter(receiver=self.request.user).order_by('timestamp').reverse()[:3]
        context['number_of_notification'] =  Notification.objects.filter(receiver=self.request.user).count()
        context['has_notifications'] =  Notification.objects.filter(receiver=self.request.user).exists()
        context['has_not_seen_message'] = ConversationPartner.objects.filter(current_user=self.request.user, have_new_message=True).exists()
        return context

    
class QuestionInDashboardView(DetailView):
    model = Users
    template_name = 'dashboard/question_in_dashboard.html'
    slug_field = 'username'
    slug_url_kwarg = 'username'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.object
        context['number_of_following_user'] = FollowForUser.objects.filter(user=user).count()
        context['number_of_followed_user'] = FollowForUser.objects.filter(followed_user=user).count()
        context['asked_questions'] = user.questions_set.filter(is_anonymous=False).order_by('created_at').reverse().all()
        context['job_experiences'] = JobExperience.objects.filter(user=user).order_by('job_date').reverse().all()
        context['newest_users_list'] = Users.objects.filter(state='現役台湾留学生').order_by('joined_at').reverse()[:4]
        if user != self.request.user:
            context['is_user_following'] = FollowForUser.objects.filter(user=self.request.user, followed_user=user).exists()
            if context['is_user_following']:
                context['following_message_for_javascript'] = 'フォロー中'
            else:
                context['following_message_for_javascript'] = 'フォロー'
        context['notification_lists'] =  Notification.objects.filter(receiver=self.request.user).order_by('timestamp').reverse()[:3]
        context['number_of_notification'] =  Notification.objects.filter(receiver=self.request.user).count()
        context['has_notifications'] =  Notification.objects.filter(receiver=self.request.user).exists()
        context['has_not_seen_message'] = ConversationPartner.objects.filter(current_user=self.request.user, have_new_message=True).exists()
        return context

templates/dashboard/question_in_dashboard.html
{% extends 'base.html' %}
{% load static %}

{% block head_content%}
{% endblock %}


{% block header %}
{% include 'header.html' %}
{% endblock %}


{% block content %}
<!-- **************** MAIN CONTENT START **************** -->
<main>
    <!-- Container START -->
    <div class="container">
        <div class="row g-4">
        <!-- Main content START -->
        <div class="col-lg-8 vstack gap-4">
            <!-- My profile START -->
            <div class="card">
                <!-- Cover image -->
                <div class="h-200px rounded-top" style="background-color:{{ object.individual_theme_color }}; background-position: center; background-size: cover; background-repeat: no-repeat;"></div>
                <!-- Card body START -->
                <div class="card-body py-0">
                <div class="d-sm-flex align-items-start text-center text-sm-start">
                    <div>
                    <!-- Avatar -->
                    <div class="avatar avatar-xxl mt-n5 mb-3">
                        <img class="avatar-img rounded-circle border border-white border-3" src="{{ object.picture.url }}" alt="プロフィール写真">
                    </div>
                    </div>
                    <div class="ms-sm-4 mt-sm-3">
                    <!-- Info -->
                    <h1 class="mb-0 h5">
                        {{ object.name }} 
                        {% if object.is_verified %}
                        <i class="bi bi-patch-check-fill text-primary small"></i>
                        {% endif %}
                    </h1>
                    <p>@{{ object.username }}</p>
                    <p>
                        <ul class="list-inline mb-0 text-center text-sm-start mt-3 mt-sm-0">
                            <li class="list-inline-item">フォロワー<strong id="number-of-followed-user">{{ number_of_followed_user }}</strong>人</li>
                            <li class="list-inline-item">フォロー中<strong>{{ number_of_following_user }}</strong>人</li>
                        </ul>
                    </p>
                    </div>
                    <!-- Button -->
                    <div class="d-flex mt-3 justify-content-center ms-sm-auto">
                    {% if user.id == object.id %}
                    <div class="dropdown ms-3" style="margin-right:4px;">
                        <a href="#" class="btn btn-sm btn-secondary-soft" id="eventActionShare" data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="bi bi-share-fill"></i>
                        </a>
                        <!-- Dropdown menu -->
                        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="eventActionShare">
                            <li style="text-align:center;">SNSでアカウントをシェア</li>
                            <li><hr class="dropdown-divider"></li>
                            <li>
                                <a class="dropdown-item" href="https://twitter.com/share?url={{ request.scheme }}://{{ request.get_host }}{{ request.path }}" target="_blank" rel="nofollow">
                                <i class="bi bi-twitter" style="color:#36B5F7;"></i> Twitter
                                </a>
                            </li>
                            <li>
                                <a class="dropdown-item" href="https://www.facebook.com/share.php?u={{ request.scheme }}://{{ request.get_host }}{{ request.path }}&t={{ object.username }}" target="_blank" rel="nofollow">
                                <i class="bi bi-facebook" style="color:#368AF7;"></i> Facebook
                                </a>
                            </li>
                            <li>
                                <a class="dropdown-item" href="https://www.instagram.com/share?url={{ request.scheme }}://{{ request.get_host }}{{ request.path }}" target="_blank" rel="nofollow">
                                    <i class="bi bi-instagram" style="color:#EE4CAC;"></i> Instagram
                                </a>
                            </li>
                            <li>
                                <a class="dropdown-item" href="https://line.me/R/msg/text/?{{ request.scheme }}://{{ request.get_host }}{{ request.path }}" target="_blank" rel="nofollow">
                                    <i class="bi bi-line" style="color:#1DAF58;"></i> Line
                                </a>
                            </li>
                        </ul>
                    </div>
                    <a href="{% url 'accounts:account_setting' object.username  %}"><button class="btn btn-danger-soft me-2" type="button"> <i class="bi bi-pencil-fill pe-1"></i> 編集 </button></a>
                    {% elif is_user_following %}
                    <a href="{% url 'chat:create_chatroom' object.username %}"><button class="btn btn-primary-soft me-2" type="button"> <i class="bi bi-chat-dots-fill pe-1"></i> メッセージ </button></a>
                    <button class="btn btn-danger-soft me-2" type="button" id="ajax-follow-for-user"> <i class="bi bi-person-heart pe-1"></i> <span id="following-message-for-javascript">{{ following_message_for_javascript }}<span> </button>
                    {% else %}
                    <a href="{% url 'chat:create_chatroom' object.username %}"><button class="btn btn-primary-soft me-2" type="button"> <i class="bi bi-chat-dots-fill pe-1"></i> メッセージ </button></a>
                    <button class="btn btn-info-soft me-2" type="button" id="ajax-follow-for-user"> <i class="bi bi-person-heart pe-1"></i> <span id="following-message-for-javascript">{{ following_message_for_javascript }}<span> </button>
                    {% endif %}
                    </div>
                </div>
                <!-- Description -->
                <div>
                    <p>{{ object.description }}</p>
                </div>
                <!-- List profile -->
                <ul class="list-inline mb-0 text-center text-sm-start mt-3 mt-sm-0">
                    <li class="list-inline-item"><i class="bi bi-person me-1"></i> {{ object.state }}</li>
                    {% if object.state == '現役台湾留学生' or object.state == '台湾留学卒業生' %}
                    <li class="list-inline-item"><i class="bi bi-pen me-1"></i>  {{ object.school }} / {{ object.major }}</li>
                    {% else %}
                    {% endif %}
                </ul>
                </div>
                <!-- Card body END -->

                <div class="card-footer mt-3 pt-2 pb-0">
                <!-- Nav profile pages -->
                <ul class="nav nav-bottom-line align-items-center justify-content-center justify-content-md-start mb-0 border-0">
                    <li class="nav-item"> <a class="nav-link" href="{% url 'dashboard:post_in_dashboard' object.username %}"> 投稿 </a> </li>
                    <!-- ユーザーの所属が現役台湾留学生or台湾留学卒業生なら、大学の口コミタブを表示 -->
                    {% if object.state == '現役台湾留学生' or object.state == '台湾留学卒業生' %}
                    <li class="nav-item"> <a class="nav-link" href="{% url 'dashboard:review_in_dashboard' object.username %}"> 口コミ </a> </li>
                    {% endif %}
                    <li class="nav-item"> <a class="nav-link active" href="{% url 'dashboard:question_in_dashboard' object.username %}"> 質問 </a> </li>
                    <li class="nav-item"> <a class="nav-link" href="{% url 'dashboard:following_in_dashboard' object.username %}"> フォロー中 <span class="badge bg-success bg-opacity-10 text-success small"> {{ number_of_following_user }}</span> </a> </li>
                    <li class="nav-item"> <a class="nav-link" href="{% url 'dashboard:followed_in_dashboard' object.username %}"> フォロワー <span class="badge bg-success bg-opacity-10 text-success small" id="number-of-followed-user"> {{ number_of_followed_user }}</span> </a> </li>
                </ul>
                </div>
            </div>
            <!-- My profile END -->

            <!-- Events START -->
            <div class="card">
                <!-- Card header START -->
                <div class="card-header d-sm-flex align-items-center justify-content-between border-0 pb-0">
                <h5>@{{ object.username }}がした質問一覧</h5>
                <!-- Button modal -->
                <a class="btn btn-primary-soft btn-sm" href="{% url 'questions:ask_question' %}"> <i class="fa-solid fa-plus pe-1"></i> 質問する</a>
                </div>
                <!-- Card header END -->
                <!-- Card body START -->
                <div class="card-body">
                <!-- Upcoming event START -->
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    <strong>質問一覧:</strong> 質問一覧はこちらから
                    <a href="{% url 'questions:question' %}" class="btn btn-xs btn-success ms-md-4">一覧を見る</a>
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                <!-- Upcoming event END -->
                <!-- Events list START -->
                {% for asked_question in asked_questions %}
                <div class="row">
                    <div class="d-sm-flex align-items-center">
                    <div class="ms-sm-4 mt-2 mt-sm-0">
                        <!-- Info -->
                        {% if asked_question.category == 'university' %}
                        <span><a href="{% url 'questions:categorized_questions' category='university' %}" class="badge bg-primary bg-opacity-10 text-primary mb-2 fw-bold">大学</a></span>
                        {% elif asked_question.category == 'foods' %}
                        <span><a href="{% url 'questions:categorized_questions' category='foods' %}" class="badge bg-primary bg-opacity-10 text-primary mb-2 fw-bold">食事</a></span>
                        {% elif asked_question.category == 'study' %}
                        <span><a href="{% url 'questions:categorized_questions' category='study' %}" class="badge bg-primary bg-opacity-10 text-primary mb-2 fw-bold">勉強</a></span>
                        {% elif asked_question.category == 'job' %}
                        <span><a href="{% url 'questions:categorized_questions' category='job' %}" class="badge bg-primary bg-opacity-10 text-primary mb-2 fw-bold">就活</a></span>
                        {% else %}
                        <span><a href="{% url 'questions:categorized_questions' category='life' %}" class="badge bg-primary bg-opacity-10 text-primary mb-2 fw-bold">人生</a></span>
                        {% endif %}

                        {% if asked_question.university %}
                        <span><a href="{% url 'questions:list_of_questions_for_each_university' pk=asked_question.university.id %}" class="badge bg-primary bg-opacity-10 text-primary mb-2 fw-bold">{{ asked_question.university }}</a></span>
                        {% endif %}

                        <ul class="nav nav-stack">
                        <li class="nav-item">
                            <strong><span style="color:#FF1474; font-size:20px;">{{ asked_question.answerforquestion_set.all.count }}</span> 回答</strong>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'questions:question_detail' asked_question.id %}"><p> {{ asked_question.content }}</p></a>
                        </li>
                        <li class="nav-item">
                            {{ asked_question.created_at }} 
                        </li>
                        </ul>
                    </div>
                    </div>
                </div>
                <!-- Events list END -->
                <hr>
                {% empty %}
                <p>質問はまだありません。</p>
                {% endfor %}
                </div>
                <!-- Card body END -->
            </div>
            <!-- Events START -->
        </div>
        <!-- Main content END -->

        {% include 'dashboard/sidebar.html' %}

        </div> <!-- Row END -->
    </div>
    <!-- Container END -->
    
    <script type="text/javascript">
        /* ユーザーフォローの非同期通信 */
        document.getElementById('ajax-follow-for-user').addEventListener('click', e => {
            e.preventDefault();
            const url = '{% url "accounts:follow_for_user" %}';
            fetch(url, {
                method: 'POST',
                body: `followed_user_pk={{object.pk}}`,
                headers: {
                'Content-Type': 'application/x-www-form-urlencoded; charset=utf-8',
                'X-CSRFToken': '{{ csrf_token }}',
                },
            }).then(response => {
                return response.json();
            }).then(response => {
                // フォロー数を書き換える
                const counter = document.getElementById('number-of-followed-user')
                counter.textContent = response.number_of_followed_user
                const following_message = document.getElementById('following-message-for-javascript')
                following_message.textContent = response.following_message_for_javascript
                const icon = document.getElementById('ajax-follow-for-user')
                // 作成した場合はハートを塗る
                if (response.method == 'create') {
                icon.classList.remove('btn-info-soft')
                icon.classList.add('btn-danger-soft')
                icon.id = 'ajax-follow-for-user'
                } else {
                icon.classList.remove('btn-danger-soft')
                icon.classList.add('btn-info-soft')
                icon.id = 'ajax-follow-for-user'
                }
            }).catch(error => {
                console.log(error);
            });
        });
    </script>
</main>
<!-- **************** MAIN CONTENT END **************** -->
{% endblock %}