Looben/urls.py
from cgitb import handler
import sre_compile
from django.contrib import admin
from django.urls import path, include 
from django.conf import settings
from django.conf.urls.static import static

from accounts.views import page_not_found, server_error


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('reviews.urls')),
    path('', include('dashboard.urls')),
    path('', include('job.urls')),
    path('', include('study_abroad_information.urls')),
    path('', include('questions.urls')),
    path('', include('chat.urls')),
    path('', include('contact_form.urls')),
    path('', include('notifications.urls')),
]

handler404 = page_not_found
handler500 = server_error

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

contact_form/urls.py
from django.urls import path
from . import views


app_name = 'contact_form'

urlpatterns = [
    path('privacy_and_safety/', views.PrivacyAndSafetyView.as_view(), name='privacy_and_safety'),
    path('contact/', views.ContactFormView.as_view(), name='contact_form'),
]

dashboard/urls.py
from django.urls import path 

from . import views

app_name = 'dashboard'

urlpatterns = [
    path('<slug:username>/post_in_dashboard', views.PostInDashboardView.as_view(), name='post_in_dashboard'),
    path('<slug:username>/review_in_dashboard', views.ReviewInDashboardView.as_view(), name='review_in_dashboard'),
    path('<slug:username>/following_in_dashboard', views.FollowingInDashboardView.as_view(), name='following_in_dashboard'),
    path('<slug:username>/followed_in_dashboard', views.FollowedInDashboardView.as_view(), name='followed_in_dashboard'),
    path('<slug:username>/question_in_dashboard', views.QuestionInDashboardView.as_view(), name='question_in_dashboard'),
]

job/urls.py
from django.urls import path
from . import views


app_name = 'job'

urlpatterns = [
        path('create_job_experience/', views.create_job_experience, name='create_job_experience'),
        path('update_job_experience/<int:pk>', views.UpdateJobExperienceView.as_view(), name='update_job_experience'),
        path('delete_job_experience/<int:pk>', views.DeleteJobExperienceView.as_view(), name='delete_job_experience'),
]

study_abroad_information/urls.py
from django.urls import path
from . import views

app_name = 'study_abroad_information'

urlpatterns = [
    path('create_information_post/', views.create_information_post, name='create_information_post'),
    path('information_post_list/', views.InformationPostListView.as_view(), name='information_post_list'),
    path('in_order_information_post_list/', views.InOrderInformationPostListView.as_view(), name='in_order_information_post_list'), 
    path('edit_information_post/<int:pk>', views.EditInformationPostView.as_view(), name='edit_information_post'), 
    path('delete_information_post/<int:pk>', views.DeleteInformationPostView.as_view(), name='delete_information_post'), 
]

study_abroad_information/models.py
from django.db import models
from django.utils import timezone

from accounts.models import Users


class StudyAbroadInformation(models.Model):
    title = models.CharField('タイトル', max_length=50)
    meta_description = models.TextField('メタデスクリプション', blank=True, max_length=150)
    url = models.CharField('url', max_length=600, default='#')
    top_image = models.FileField('サムネイル画像', upload_to='information/', default='blog/top_image/top_image.png')
    created_at = models.DateField('作成日', default=timezone.now)
    is_official = models.BooleanField(default=False)
    tag = models.CharField('タグ', max_length=25, null=True)
    author = models.ForeignKey(
        Users, on_delete=models.CASCADE
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = '留学情報投稿'
        verbose_name_plural = '留学情報投稿'

study_abroad_information/forms.py
from django import forms

from .models import StudyAbroadInformation

class CreateInformationPostForm(forms.ModelForm):
    title = forms.CharField(label='タイトル', widget=forms.TextInput(attrs={
        'class': 'form-control', 
        'placeholder': 'タイトル記入欄', 
        'id': 'title',
        }))
    meta_description = forms.CharField(label='メタデスクリプション', widget=forms.Textarea(attrs={
        'class': 'form-control', 
        'rows': '5',
        'type': 'textarea',
        'id': 'meta_description',
        }))
    url = forms.CharField(label='URL', widget=forms.TextInput(attrs={
        'class': 'form-control', 
        'placeholder': 'URL記入欄', 
        'id': 'url',
        }))
    top_image = forms.FileField(label='サムネイル画像', required=False, widget=forms.FileInput(attrs={
        'class': 'form-control', 
        'type': 'file',
        'id': 'formFile',
        }))
    tag = forms.CharField(label='タグ', widget=forms.TextInput(attrs={
        'class': 'form-control', 
        'id': 'tag',
        }))
    
    
    class Meta:
        model = StudyAbroadInformation
        fields = ['title', 'meta_description', 'url', 'top_image', 'tag']
        
        
class EditInformationPostForm(forms.ModelForm):
    title = forms.CharField(label='タイトル', widget=forms.TextInput(attrs={
        'class': 'form-control', 
        'placeholder': 'タイトル記入欄', 
        'id': 'title',
        }))
    meta_description = forms.CharField(label='メタデスクリプション', widget=forms.Textarea(attrs={
        'class': 'form-control', 
        'rows': '5',
        'type': 'textarea',
        'id': 'meta_description',
        }))
    url = forms.CharField(label='URL', widget=forms.TextInput(attrs={
        'class': 'form-control', 
        'placeholder': 'URL記入欄', 
        'id': 'url',
        }))
    top_image = forms.FileField(label='サムネイル画像', required=False, widget=forms.FileInput(attrs={
        'class': 'form-control', 
        'type': 'file',
        'id': 'formFile',
        }))
    tag = forms.CharField(label='タグ', widget=forms.TextInput(attrs={
        'class': 'form-control', 
        'id': 'tag',
        }))
    
    
    class Meta:
        model = StudyAbroadInformation
        fields = ['title', 'meta_description', 'url', 'top_image', 'tag']

study_abroad_information/views.py
from django.shortcuts import render, redirect
from django.views.generic.base import View
from django.views.generic.edit import UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.shortcuts import get_object_or_404 

from .forms import CreateInformationPostForm, EditInformationPostForm
from .models import StudyAbroadInformation
from accounts.models import FollowForUser
from accounts import contribution_calculation
from notifications.models import Notification
from chat.models import ConversationPartner


class CheckForUserMatchMixin(LoginRequiredMixin, UserPassesTestMixin):
    
    def test_func(self):
        target_information_post = get_object_or_404(StudyAbroadInformation, pk=self.kwargs['pk'])
        return self.request.user == target_information_post.author
        
    def handle_no_permission(self):
        return JsonResponse(
            {'message': 'Only user who made this author have access to this view'}
        )
        

@login_required
def create_information_post(request):
    create_information_post_form = CreateInformationPostForm(request.POST or None)
    if create_information_post_form.is_valid():
        create_information_post_form.instance.author = request.user
        create_information_post_form.save()
        contribution_calculation.for_creating_post(author=request.user)
        # フォロワーへの留学情報作成の通知を作成
        for follow in FollowForUser.objects.filter(followed_user=request.user).all():
            create_information_post_notification = Notification(sender=request.user, receiver=follow.user, message= str(request.user.username) + 'が新しく留学情報を投稿しました。')
            create_information_post_notification.save()
        return redirect('study_abroad_information:information_post_list')
    notification_lists =  Notification.objects.filter(receiver=request.user).order_by('timestamp').reverse()[:3]
    number_of_notification =  Notification.objects.filter(receiver=request.user).count()
    has_notifications =  Notification.objects.filter(receiver=request.user).exists()
    has_not_seen_message = ConversationPartner.objects.filter(current_user=request.user, have_new_message=True).exists()
    return render(
        request, 'study_abroad_information/create_information_post.html', context={
            'create_information_post_form': create_information_post_form,
            'notification_lists': notification_lists,
            'number_of_notification': number_of_notification,
            'has_notifications': has_notifications,
            'has_not_seen_message': has_not_seen_message
        }
    )
    
    
class DeleteInformationPostView(CheckForUserMatchMixin, DeleteView):
    template_name = 'study_abroad_information/delete_information_post.html'
    model = StudyAbroadInformation
    
    def get_success_url(self):
        return reverse_lazy('dashboard:post_in_dashboard', kwargs={'username': self.object.author.username}) 
    
    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['notification_lists'] =  Notification.objects.filter(receiver=self.request.user).order_by('timestamp').reverse()[:3]
        context['number_of_notification'] =  Notification.objects.filter(receiver=self.request.user).count()
        context['has_notifications'] =  Notification.objects.filter(receiver=self.request.user).exists()
        context['has_not_seen_message'] = ConversationPartner.objects.filter(current_user=self.request.user, have_new_message=True).exists()
        return context
    

class EditInformationPostView(CheckForUserMatchMixin, UpdateView):
    template_name = 'study_abroad_information/edit_information_post.html'
    form_class = EditInformationPostForm
    model = StudyAbroadInformation
    
    def get_success_url(self):
        return reverse_lazy('dashboard:post_in_dashboard', kwargs={'username': self.object.author.username}) 
    
    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['notification_lists'] =  Notification.objects.filter(receiver=self.request.user).order_by('timestamp').reverse()[:3]
        context['number_of_notification'] =  Notification.objects.filter(receiver=self.request.user).count()
        context['has_notifications'] =  Notification.objects.filter(receiver=self.request.user).exists()
        context['has_not_seen_message'] = ConversationPartner.objects.filter(current_user=self.request.user, have_new_message=True).exists()
        return context
    
    
class InformationPostListView(LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        user = request.user
        number_of_following_user = FollowForUser.objects.filter(user=user).count()
        number_of_followed_user = FollowForUser.objects.filter(followed_user=user).count()
        number_of_information_post = StudyAbroadInformation.objects.filter(author=user).count()
        newest_information_posts = StudyAbroadInformation.objects.filter(is_official=False).order_by('-created_at')[:6]
        official_information_post_lists = StudyAbroadInformation.objects.filter(is_official=True).order_by('-created_at')[:3]
        notification_lists =  Notification.objects.filter(receiver=user).order_by('timestamp').reverse()[:3]
        number_of_notification =  Notification.objects.filter(receiver=user).count()
        has_notifications =  Notification.objects.filter(receiver=user).exists()
        has_not_seen_message = ConversationPartner.objects.filter(current_user=request.user, have_new_message=True).exists()
        if 'search' in self.request.GET:
            keyword_query = request.GET.get('search')
            if keyword_query == '':
                searched_posts = []
                number_of_searched_posts = 0
                user_searched_something = False
            else:
                posts = list(StudyAbroadInformation.objects.all())
                searched_posts = []
                for post in posts:
                    if keyword_query in post.meta_description:
                        searched_posts.append(post)
                number_of_searched_posts = len(searched_posts)
                user_searched_something = True
        else:
            searched_posts = []
            number_of_searched_posts = 0
            user_searched_something = False
        return render(request, 'study_abroad_information/information_post_list.html', {
            'number_of_following_user': number_of_following_user,
            'number_of_followed_user': number_of_followed_user,
            'number_of_information_post': number_of_information_post,
            'newest_information_posts': newest_information_posts,
            'official_information_post_lists': official_information_post_lists,
            'number_of_searched_posts': number_of_searched_posts,
            'user_searched_something': user_searched_something,
            'searched_posts': searched_posts,
            'notification_lists': notification_lists,
            'number_of_notification': number_of_notification,
            'has_notifications': has_notifications,
            'has_not_seen_message': has_not_seen_message
            })
    
    
class InOrderInformationPostListView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        information_posts_order_by_date = StudyAbroadInformation.objects.filter(is_official=False).order_by('-created_at')[:30]
        official_information_post_lists = StudyAbroadInformation.objects.filter(is_official=True).order_by('-created_at')[:30]
        notification_lists =  Notification.objects.filter(receiver=request.user).order_by('timestamp').reverse()[:3]
        number_of_notification =  Notification.objects.filter(receiver=request.user).count()
        has_notifications =  Notification.objects.filter(receiver=request.user).exists()
        has_not_seen_message = ConversationPartner.objects.filter(current_user=request.user, have_new_message=True).exists()
        return render(request, 'study_abroad_information/in_order_information_post.html', {
            'information_posts_order_by_date': information_posts_order_by_date,
            'official_information_post_lists': official_information_post_lists,
            'notification_lists': notification_lists,
            'number_of_notification': number_of_notification,
            'has_notifications': has_notifications,
            'has_not_seen_message': has_not_seen_message
            })

templates/study_abroad_information/delete_information_post.html
{% extends 'base.html'%}
{% load static %}

{% block head_content %}
{% endblock %}


{% block header %}
{% include 'header.html' %}
{% endblock %}


{% block content %}
<!-- **************** MAIN CONTENT START **************** -->
<main>
    <!-- Container START -->
    <div class="container">
        <div class="row">
            <!-- Main content START -->
            <div class="col-md-11 mx-auto">
            <!-- Create a page START -->
            <div class="card">
                <!-- Title START -->
                <div class="card-header border-0 pb-0">
                <h1 class="h4 card-title mb-0">投稿削除画面</h1>
                </div>
                <!-- Title END -->

                <!-- Create a page form START -->
                <div class="card-body">
                <form class="row g-3 mt-4" method="post">
                    {% csrf_token %}

                    <div class="col-12">
                        <label class="form-label">タイトル</label>
                        <input class="form-control" type="text" value="{{ object.title }}" aria-label="Disabled input example" disabled readonly>
                    </div>

                    <div class="col-12">
                        <label class="form-label">共有URL</label>
                        <input class="form-control" type="text" value="{{ object.url }}" aria-label="Disabled input example" disabled readonly>
                    </div>

                    <div class="col-8">
                        <label class="form-label">サムネイル画像</label>
                        <input class="form-control" type="text" value="{{ object.top_image }}" aria-label="Disabled input example" disabled readonly>
                    </div>

                    <div class="col-12">
                        <label class="form-label">メタデスクリプション</label>
                        <input class="form-control" type="text" value="{{ object.meta_description }}" aria-label="Disabled input example" disabled readonly>
                    </div>

                    <div class="col-12">
                        <label class="form-label">タグ</label>
                        <input class="form-control" type="text" value="#{{ object.tag }}" aria-label="Disabled input example" disabled readonly>
                    </div>

                    <!-- Button  -->
                    <div class="col-12 text-end">
                    <button type="submit" class="btn btn-danger mb-0">削除</button>
                    </div>
                </form>
                </div>
                <!-- Create a page form END -->
            </div>
            <!-- Create a page END -->
            </div>
    
        </div> <!-- Row END -->
    </div>
    <!-- Container END --> 
</main>
<!-- **************** MAIN CONTENT END **************** -->
{% endblock %}

templates/study_abroad_information/information_post_list.html
{% extends 'base.html' %}
{% load static %}


{% block header %}
{% include 'header.html' %}
{% endblock %}


{% block content %}
<main> 

    <!-- Container START -->
    <div class="container-fluid">

        <!-- Sidenav START -->
        <div class="navbar navbar-vertical navbar-light">
            <div class="offcanvas offcanvas-start custom-scrollbar rounded pt-3" tabindex="-1" id="navbarVerticaloffcanvas">
            <div class="offcanvas-body pt-5 pt-lg-0">
                <!-- Card START -->
                
                <!-- Avatar -->
                <div class="avatar avatar-lg mb-3">
                    <a href="{% url 'dashboard:post_in_dashboard' user.username %}"><img class="avatar-img rounded-circle border border-white border-3" src="{{ user.picture.url }}" alt="{{ user.username }}"></a>
                </div>
                <!-- Info -->
                <h5 class="mb-0"> 
                    <a href="{% url 'dashboard:post_in_dashboard' user.username %}">
                        {{ user.name }} 
                        {% if user.is_verified %}
                        <i class="bi bi-patch-check-fill text-primary small"></i>
                        {% endif %}
                    </a> 
                </h5>
                <small>{{ user.school }}</small>
                <!-- User stat START -->
                <div class="hstack gap-2 gap-xl-3 mt-3">
                    <!-- User stat item -->
                    <div>
                    <h6 class="mb-0">{{ number_of_information_post }}</h6>
                    <small>Post</small>
                    </div>
                    <!-- Divider -->
                    <div class="vr"></div>
                    <!-- User stat item -->
                    <div>
                    <h6 class="mb-0">{{ number_of_followed_user }}</h6>
                    <small>Followers</small>
                    </div>
                    <!-- Divider -->
                    <div class="vr"></div>
                    <!-- User stat item -->
                    <div>
                    <h6 class="mb-0">{{ number_of_following_user }}</h6>
                    <small>Following</small>
                    </div>
                </div>
                <!-- User stat END -->
    
                <!-- Divider -->
                <hr>
    
                <!-- Side Nav START -->
                <ul class="nav nav-link-secondary flex-column fw-bold gap-2">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'dashboard:post_in_dashboard' user.username %}"> <img class="me-2 h-20px fa-fw" src="{% static 'images/icon/certificate-outline-filled.svg' %}" alt="blog"><span>投稿 </span></a>
                    </li>
                    {% if user.state == '現役台湾留学生' or user.state == '台湾留学卒業生' %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'dashboard:review_in_dashboard' user.username %}"> <img class="me-2 h-20px fa-fw" src="{% static 'images/icon/clipboard-list-outline-filled.svg' %}" alt="review"><span>口コミ </span></a>
                    </li>                    
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'dashboard:question_in_dashboard' user.username %}"> <img class="me-2 h-20px fa-fw" src="{% static 'images/icon/bulb-curvy-outline-filled.svg' %}" alt="question"><span>質問 </span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'dashboard:following_in_dashboard' user.username %}"> <img class="me-2 h-20px fa-fw" src="{% static 'images/icon/person-outline-filled.svg' %}" alt="following"><span>フォロー中 </span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'dashboard:followed_in_dashboard' user.username %}"> <img class="me-2 h-20px fa-fw" src="{% static 'images/icon/person-girl-outline-filled.svg' %}" alt="followd"><span>フォロワー </span></a>
                    </li>
                </ul>
                <!-- Side Nav END -->
                </div>
            </div>
            </div>
            <!-- Sidenav END -->
    
            <!-- Main content START -->
            <div class="page-content">
            <div class="row mb-4">
                <div class="col-12">
                <!-- Video main feed -->
                <div class="rounded py-4 py-sm-5 overflow-hidden position-relative" style="background-image:url({% static 'images/bg/wave.jpg' %}); background-position: center center; background-size: cover; background-repeat: no-repeat;">
                    <div class="bg-overlay bg-dark opacity-5"></div>
                    <div class="p-4 p-sm-5 position-relative">
                    <h1 class="text-white">知りたい情報がここにある</h1>
                    <p class="text-white">あなたも、Loobenで留学情報を共有しませんか? <a href="{% url 'study_abroad_information:create_information_post' %}">投稿する</a></p>
                    <!-- Form START -->
                    {% csrf_token %}
                    <form class="row g-3" method="get">
                    <div class="col-md-6">
                        <!-- Where -->
                        <div class="input-group">
                        <input class="form-control form-control-lg me-1 pe-5" type="search" placeholder="キーワード検索" name="search">
                        </div>
                    </div>
                    <div class="col-md-2 d-grid">
                        <!-- Search -->
                        <button class="btn btn-lg btn-primary" type="submit">検索</button>
                    </div>
                    </form>
                    <!-- Form END -->
                    </div>
                </div>
                <!-- Video main END -->
                </div>
            </div>
                

            {% if user_searched_something %}
            <div class="row g-3 mb-4">
                <div class="col-12 mt-4">
                <div class="d-sm-flex justify-content-between align-items-center">
                    <h5 class="mb-md-0">検索結果<strong style="color:#FF1474;">{{ number_of_searched_posts }}</strong>件</h5>
                </div>
                </div>
                {% for searched_post in searched_posts %}
                <div class="col-sm-6 col-md-4 col-xl-3 col-xxl-2">
                <!-- Video START -->
                <div class="card position-relative h-100">
                    <!-- Video image -->
                    <div class="card-image">
                    <a href=""><img class="card-img-top" src="{{ searched_post.top_image.url }}" alt="blog_top_image"></a>
                    </div>
                    <!-- Video info -->
                    <div class="card-body">
                    <!-- Video title  -->
                    <h6> <a class="stretched-link" href=""> {{ searched_post.title }} </a> </h6>
                    <div class="d-flex mt-3">
                        <!-- Avatar -->
                        <div class="avatar avatar-xxs me-2">
                        <img class="avatar-img rounded-circle" src="{{ searched_post.author.picture.url }}" alt="{{ searched_post.author.username }}">
                        </div>
                        <!-- Avatar name -->
                        <div>
                        <h6 class="mb-0 lh-1"> 
                            <a href="{% url 'dashboard:post_in_dashboard' searched_post.author.username %}"> 
                                {{ searched_post.author.name }} 
                                {% if searched_post.author.is_verified %}
                                <i class="bi bi-patch-check-fill text-primary small"></i>
                                {% endif %}
                            </a> 
                        </h6>
                        </div>
                    </div>
                    </div>
                </div>
                <!-- Video END -->
                </div>
                {% endfor %}
            </div>
            {% endif %}

            <div class="row g-3 mb-4">
                <div class="col-12 mt-4">
                <div class="d-sm-flex justify-content-between align-items-center">
                    <h5 class="mb-md-0">最新情報 </h5>
                </div>
                </div>
                {% for newest_information_post in newest_information_posts %}
                <div class="col-sm-6 col-md-4 col-xl-3 col-xxl-2">
                <!-- Video START -->
                <div class="card position-relative h-100">
                    <!-- Video image -->
                    <div class="card-image">
                    <a href="{{ newest_information_post.url }}"><img class="card-img-top" src="{{ newest_information_post.top_image.url }}" alt="top_image"></a>
                    </div>
                    <!-- Video info -->
                    <div class="card-body">
                    <!-- Video title  -->
                    <h6> <a class="stretched-link" href="{{ newest_information_post.url }}"> {{ newest_information_post.title }} </a> </h6>
                    <div class="d-flex mt-3">
                        <!-- Avatar -->
                        <div class="avatar avatar-xxs me-2">
                        <img class="avatar-img rounded-circle" src="{{ newest_information_post.author.picture.url }}" alt="{{ newest_information_post.author.username }}">
                        </div>
                        <!-- Avatar name -->
                        <div>
                        <h6 class="mb-0 lh-1"> 
                            <a href="{% url 'dashboard:post_in_dashboard' newest_information_post.author.username %}"> 
                                {{ newest_information_post.author.name }} 
                                {% if newest_information_post.author.is_verified %}
                                <i class="bi bi-patch-check-fill text-primary small"></i>
                                {% endif %}
                            </a> 
                        </h6>
                        </div>
                    </div>
                    </div>
                </div>
                <!-- Video END -->
                </div>
                {% empty %}
                <p>留学情報はまだありません。<p>
                {% endfor %}
            </div>
    
            <!-- Official trailer START -->
            <div class="row g-3 mb-4">
                <div class="col-12 mt-4">
                <div class="d-sm-flex justify-content-between align-items-center">
                    <h5 class="mb-md-0">オフィシャル情報 </h5>
                    <a class="btn btn-sm btn-primary" href="{% url 'study_abroad_information:in_order_information_post_list' %}">もっとみる</a>
                </div>
                </div>
                {% for official_information_post in official_information_post_lists %}
                <div class="col-sm-6 col-lg-4">
                <!-- Video START -->
                <div class="card h-100">
                    <!-- Video image -->
                    <div class="card-image">
                        <a href="{{ official_information_post.url }}"><img class="card-img-top" src="{{ official_information_post.top_image.url }}" alt="top_image"></a>
                    </div>
                    <!-- Video info -->
                    <div class="card-body position-relative">
                    <!-- Video title  -->
                    <h6> <a class="stretched-link" href="{{ official_information_post.url }}"> {{ official_information_post.title }} </a> </h6>
                    <div class="d-flex mt-2">
                        <!-- Avatar -->
                        <div class="avatar avatar-xxs me-2">
                        <img class="avatar-img rounded-circle" src="{{ official_information_post.author.picture.url }}" alt="{{ official_information_post.author.username }}">
                        </div>
                        <!-- Avatar name -->
                        <div>
                        <h6 class="mb-0 lh-1"> 
                            <a href="{% url 'dashboard:post_in_dashboard' official_information_post.author.username %}"> 
                            {{ official_information_post.author.name }} 
                            {% if official_information_post.author.is_verified %}
                            <i class="bi bi-patch-check-fill text-primary small"></i>
                            {% endif %}
                            </a> 
                        </h6>
                        </div>
                    </div>
                    </div>
                </div>
                <!-- Video END -->
                </div>
                {% empty %}
                <p>オフィシャル情報はまだありません。<p>
                {% endfor %}
            </div>
            <!-- Official trailer END -->
    
            <!-- footer START -->
            <footer class="card card-body">
                <div class="row g-4">
                <div class="col-md-8">
                    <!-- Footer nav START -->
                    <ul class="nav lh-1">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'contact_form:privacy_and_safety' %}">プライバシーポリシー</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'contact_form:contact_form' %}">お問い合わせ</a>
                        </li>
                    </ul>
                    <!-- Footer nav START -->
                    <!-- Copyright START -->
                    <p class="mb-0 mt-4">©2023 Looben, All Rights Reserved.</p>
                    <!-- Copyright END -->
                </div>
            </footer>
            <!-- footer END -->
        </div>
        <!-- Main content END -->

    </div>
    <!-- Container END -->
    
</main>
<!-- **************** MAIN CONTENT END **************** -->

{% endblock %}